### ISSUE TITLE
Secondary Upgrade Slot for Auto Sieves

### ISSUE THREAD

**Issue by blay09** [ModdingForBlockheads/ExCompressum#145]
For the sifter items from Omnia. Maybe something else to affect the sieve outside of the mesh.

**Comment by BrittanyDilts** [comment]
Maybe a slot for giving the Sieve Steve food to make him sieve faster (like how you give bonemeal/fertilizer to Garden Cloches). Could be tiered (higher saturation, faster Steve?). I say yes, please. Waiting on Sieve Steve is excruciating.

**Comment by BlayTheNinth** [comment]
Closing since Omnia is no longer updating and Sequentia uses sieve items again.
