### ISSUE TITLE
A watched sieve never finishes

### ISSUE THREAD

**Issue by daman4567** [ModdingForBlockheads/ExCompressum#249]
If you right click a sieve to see the interface while it's in the middle of sieving an item, it will start at 0 progress.  Leave and re-enter the interface and it will reset again.  Tested in single player.

**Comment by blay09** [comment]
This is not happening to me. What version are you on?

**Comment by Stephenator0316** [comment]
Happening to me too. Playing mc 1.12.2, mod version is 3.0.26.

Environment is Windows 10.

Playing "Stoneblock" modpack

**Comment by blay09** [comment]
Tested on StoneBlock, still working fine for me. Do you have exact steps to reproduce?
